config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
resources :blog_posts
resources :comments

    root to: "users#index"
  end

  get 'profile/user_page'
  get 'your_posts' => 'blog_posts#your_posts'
  get 'user_posts' => 'blog_posts#user_posts'
  devise_for :users
  root 'blog_posts#index'
  resources :comments
  resources :blog_posts
  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/controllers/admin/blog_posts_controller.rb
module Admin
  class BlogPostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = BlogPost.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   BlogPost.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  
  def your_posts
    
  end
  
  def user_posts
    @user = User.find(params[:id])
  end
  
  

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
   @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
    authorize! :read, @blog_post
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    
    
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
    
    
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class=" container col s12 m4 l8">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :blog_entry %><br>
    <%= f.text_area :blog_entry %>
  </div>
  <div class="field cant-see-me">
    <%= f.label :blog_post_id %><br>
    <%= f.number_field :blog_post_id, value: @blog_post.id%>
    <%= f.number_field :user_id, value: current_user.id%>
  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>
</div>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<div class=" container col s12 m4 l8">
    <%= link_to 'Show', @blog_post %> |
    <%= link_to 'Back', blog_posts_path %>
</div>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Posts:</h1>



    <div class="row">
    <% @blog_posts.each do |blog_post| %>
    
        <div class="col s12 m6">
          <div class="card teal lighten-3">
            <div class="card-content white-text">
              <span class="card-title">
                <%= link_to blog_post.title, blog_post, class:"white-text" %>
              </span>
              <p>By: <i><%= link_to blog_post.user.email, user_posts_path(id: blog_post.user.id) %></i></p>
              
              <% if blog_post.blog_entry.length>100%>
                <p><%= blog_post.blog_entry[0..10] %>
                ...[<%= link_to 'Read More', blog_post, class:"white-text" %>]</p>
              <% else %>
                <p><%= blog_post.blog_entry %> </p>
              <% end %>
              
              <%= blog_post.created_at.strftime('%m/%d/%y %H:%M:%S') %>
            </div>
          
            <div class="divider"></div>
  
              <% if can? :update, blog_post %>
                 <%= link_to "Edit", edit_blog_post_path(blog_post), class: "waves-effect waves-teal btn-flat" %>
                 <%= link_to "Destroy", blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-teal btn-flat" %>
              <% else %>
                 <br><br>
              <% end %>
              
            
          </div>
        </div>
    <% end %>
    </div>
  
  


<br>
<%= link_to 'New Blog post', new_blog_post_path, class:"waves-effect waves-light btn white-text" %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card teal lighten-3">
    <div class="card-content white-text">
      <span class="card-title white-text">
      <h5>
        <%= @blog_post.title %>
      </h5>
      <p>
        <i>by</i>
        <i><%= link_to @blog_post.user.email, user_posts_path(id: @blog_post.user.id) %></i>
      </p>

      <p>
        <%= @blog_post.blog_entry %>
      </p>

      <div class="divider"></div>
      <% if can? :update, @blog_post %>
        <%= link_to "Edit", edit_blog_post_path(@blog_post) %>
      <% end %>
          
    </span>
  </div>
</div>


<div class="card">
    <div class="card-content black-text">
      <span class="card-title black-text">
        Leave a Comment!
      </span>
      <p>
        <%= render 'comments/form'%>
      </p>
    </div>
</div>

<div class = "card">
  <div class="card-content">
    <span class ="card-title black-text">
      Comments
    </span>
    
    <% @blog_post.comments.each do |comment| %>
    <div class="comment comment-<%=comment.id%>" data-hidden="true" data-commentid="<%=comment.id%>">
             <p>
               <b><%= link_to comment.user.email, user_posts_path(id: comment.user.id) %></b> <i>said..</i>
               <%= link_to 'Show Comment', comments_path, class:"hidebtn waves-effect waves-teal btn-flat" =%>
             </p>
             
             <p class=""><%= comment.comment_entry%></p>
            
             <%= comment.created_at.strftime('%m/%d/%Y at %I:%M%p')%>
             <br> <div class ="divider"></div><br>
    </div>
             <%end%>
  </div>
</div>


        
      <%= link_to 'Back', blog_posts_path, class:"waves-effect waves-light btn white-text" %>  
      
      </div>
      <script src="http://code.jquery.com/jquery-2.1.3.js"></script>
      <script>
      $('.hidebtn').click(function(){
        console.log($(this).parent()[0])
        var commentID = $(this).parent()[0].dataset.commentid;
        console.log(commentID);
        var commentElement = $('.comment-' + commentID)
        
        console.log(commentElement.find('a'));
        if (commentElement[0].dataset.hidden === 'true') {
          $(this).text('HIDE COMMENT');
        } else {
          commentElement[0].dataset.hidden = 'false';
          $('.' + this.id).hide();
          $(this).text('SHOW COMMENT');
        }
      });
      </script>
    
    
    
    

app/views/blog_posts/user_posts.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %>'s Blog Posts:</h1>


 
 <div class="row">
    <% @user.blog_posts.each do |blog_post| %>
    
        <div class="col s12 m6">
          <div class="card teal lighten-3">
            <div class="card-content white-text">
              <span class="card-title">
                <%= link_to blog_post.title, blog_post, class:"white-text" %>
              </span>
              <p>By: <i><%= blog_post.user.email %></i></p>
              
              <% if blog_post.blog_entry.length>100%>
                <p><%= blog_post.blog_entry[0..10] %>
                ...[<%= link_to 'Read More', blog_post, class:"white-text" %>]</p>
              <% else %>
                <p><%= blog_post.blog_entry %> </p>
              <% end %>
              
              <%= blog_post.created_at.strftime('%m/%d/%y %H:%M:%S') %>
            </div>
          
            <div class="divider"></div>
              <% if can? :update, blog_post %>
                 <%= link_to "Edit", edit_blog_post_path(blog_post), class: "waves-effect waves-teal btn-flat" %>
                 <%= link_to "Destroy", blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-teal btn-flat" %>
              <% end %>
            
          </div>
        </div>
    <% end %>
  </div>

app/views/blog_posts/your_posts.html.erb
<p id="notice"><%= notice %></p>

<h1><%= current_user.name %>'s Blog Posts:</h1>


 
 <div class="row">
    <% current_user.blog_posts.each do |blog_post| %>
    
        <div class="col s12 m6">
          <div class="card teal lighten-3">
            <div class="card-content white-text">
              <span class="card-title">
                <%= link_to blog_post.title, blog_post, class:"white-text" %>
              </span>
              <p>By: <i><%= blog_post.user.email %></i></p>
              
              <% if blog_post.blog_entry.length>100%>
                <p><%= blog_post.blog_entry[0..10] %>
                ...[<%= link_to 'Read More', blog_post, class:"white-text" %>]</p>
              <% else %>
                <p><%= blog_post.blog_entry %> </p>
              <% end %>
              
              <%= blog_post.created_at.strftime('%m/%d/%y %H:%M:%S') %>
            </div>
          
            <div class="divider"></div>
              <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "waves-effect waves-teal btn-flat" %>
              <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-teal btn-flat" %>
            
          </div>
        </div>
    <% end %>
    </div>